### ISSUE TITLE
[FEATURE] Add Navbar to all pages

### ISSUE THREAD

**Issue by IAmRiteshKoushik** [IAmRiteshKoushik/queue-io#1]
Add simple navigation bar with the following buttons:

1. Guides
2. Static Queues
3. Multiple Queues
4. Dynamic Queues

**Comment by sagarkumardse** [comment]
can i work on this?

**Comment by IAmRiteshKoushik** [comment]
Hey @sagarkumardse, this project is currently at a very nascent stage and is being worked on by my teammates from the university. We have considered taking in open source contributions after completing the first version of the project. Thanks for reaching out!

 If you are still interested in contributing after a month, be sure to raise an Issue with regards to what can be improved and we would have happy to make upgrades to this project.

**Comment by IAmRiteshKoushik** [comment]
This issue has been resolved. Closing the issue.

**Comment by IAmRiteshKoushik** [comment]
This issue has been resolved.
